#ifndef SFMLDEMO_CHARACTERANIMATIONTYPES_H
#define SFMLDEMO_CHARACTERANIMATIONTYPES_H

enum character_animation_type
{
    CHARACTER_MOVE,
    CHARACTER_IDLE,
    CHARACTER_INSTANT_CAST
};

#endif //SFMLDEMO_CHARACTERANIMATIONTYPES_H
