#ifndef SFMLDEMO_CHARACTERANIMATIONTYPES_H
#define SFMLDEMO_CHARACTERANIMATIONTYPES_H

enum class character_animation_type
{
    MOVE,
    IDLE,
    INSTANT_CAST
};

#endif //SFMLDEMO_CHARACTERANIMATIONTYPES_H
