#ifndef SFMLDEMO_EVENTTYPE_H
#define SFMLDEMO_EVENTTYPE_H

enum class event_type
{
    SKILL_ACTIVATED,
    INSTANT_CAST_ANIMATION_ENDED,
    CHARACTER_STATS_CHANGED
};

#endif //SFMLDEMO_EVENTTYPE_H
