#ifndef SFMLDEMO_EVENTTYPE_H
#define SFMLDEMO_EVENTTYPE_H

enum class event_type
{
    SKILL_ACTIVATED,
    INSTANT_CAST_ANIMATION_ENDED,
    CHARACTER_STATS_CHANGED,

    INTERACTION_MENU_ENTRY_CLICKED,
    INTERACTION_CANCELLED,

    QUEST_ACCEPTED,
    QUEST_ADDED,
    QUEST_REMOVED,
    OBJECTIVE_COMPLETED,

    MONSTER_DIED
};

#endif //SFMLDEMO_EVENTTYPE_H
