#ifndef SFMLDEMO_ANIMATIONTYPES_H
#define SFMLDEMO_ANIMATIONTYPES_H

enum animation_types
{
    CHARACTER_WALK,
    CHARACTER_STAND,
    CHARACTER_INSTANT_CAST,
    SKILL_FIREBALL_FLY
};

#endif //SFMLDEMO_ANIMATIONTYPES_H
